# Generated by Django 3.1.3 on 2020-11-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201129_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='promote',
            field=models.BooleanField(default=False),
        ),
    ]
